"""initiaffffffl

Revision ID: 10cc9e49520a
Revises: 1da3f7a2adff
Create Date: 2025-07-19 12:37:45.625932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cc9e49520a'
down_revision = '1da3f7a2adff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('per_day_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('per_day_fee')

    # ### end Alembic commands ###
